### PR TITLE
build: bump deps

### PR DESCRIPTION
**Pull request by amaanq**
bumps dependencies to latest versions (incl. wasmtime to v22)

### CODE REVIEW

**Comment by clason** [comment]
wasmtime moved some cheese; see https://github.com/neovim/neovim/pull/28415/files#diff-b14426e2ba1297545b4a38ffef2169401940258b508a6524cb1424a1f7c06315

**Comment by clason** [comment]
It looks like you need the cmake crate to build `wasmtime-c-api` now?

**Comment by ObserverOfTime** [comment]
So is it time to use CMake as our build system?

**Comment by CGamesPlay** [comment]
Now that https://github.com/bytecodealliance/wasmtime/pull/9102 is merged and wasmtime v23.0.2 is released, it should be possible to use `23.0.2` as the version for wasmtime without requiring any build setup changes.

**Comment by clason** [comment]
That is what Max was concerned about, yes. It's not a problem for CI since GitHub runners have cmake preinstalled.

**Comment by amaanq** [comment]
Closing as outdated

**Pull request closed without merging**
