### PR TITLE
feat: implement a cache for `get_column`

### LINKED ISSUE #1626: Improve performance of `get_column`
As sketched [here](https://github.com/tree-sitter/tree-sitter/pull/1581#issuecomment-1010512449) in the PR changing `get_column` to count codepoints instead of bytes, we can create a "best effort" cache of the current column position:

1. A `column_cache` field is added to the `Lexer` struct in `lib/src/lexer.h`
2. `column_cache` is updated as `ts_lexer__advance` is called in `lib/src/lexer.c`, incrementing with each character and being set to `0` upon consuming a newline
3. If `ts_lexer_goto` is called then the `column_cache` field is set to a value indicating "unknown", possibly `-1` if given type `int32_t` or with a separate boolean `column_unknown` field in the `Lexer` state if given type `uint32_t` to match the return type of `get_column`
4. If `get_column` is called when `column_cache` is in a "known" state, the `column_cache` value is returned; otherwise, the lexer reads from the beginning of the line, updates `column_cache`, and returns the calculated value

In what cases is `ts_lexer_goto` called? I can think of the following possibilities:

1. When an external scanner is called, reads some text, then returns `false`
2. When an external scanner is called, calls `mark_end`, reads some more text, then returns `true`
3. When the internal lexer reads an identifier twice for keyword extraction
3. During error recovery
4. At the start of parsing

Are there any others? Since (1) and (2) are likely to be quite common among external scanners using `get_column`, additional caches could be added to handle those cases so calling `ts_lexer_goto` would set the value of `column_cache` to a value recorded upon entering an external scanner or calling `mark_end`. However, that would likely require changes to `lib/src/parser.c` in addition to `lib/src/lexer.c`.

### LINKED ISSUE #3433: [perf] Bad performance when call get_column frequently
### Problem

When the get_column function is called frequently, the performance of get_column will be poor. Should we improve the performance of get_column?

example:

at first:

```
$ time pn tree-sitter parse ../1mb.data
pnpm tree-sitter parse ../1mb.data  4.18s user 0.13s system 100% cpu 4.285 total
```

change the code :
```c
usize start_pos = lexer->get_column(lexer);
if(lexer->get_column(lexer) == 0) {
}
```
to
```
usize start_pos = lexer->get_column(lexer);
if(start_pos == 0) {
}
```

```console

$ time pn tree-sitter parse ../1mb.data
pnpm tree-sitter parse ../1mb.data  3.01s user 0.15s system 101% cpu 3.122 total
```

> [!NOTE]
> the data should be 1MB but not 1mb.

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by amaanq**
- _Supersedes_ #1637 
- Closes #3433
- Closes #1626

### CODE REVIEW

**Comment by amaanq** [comment]
@ahelwer I'd appreciate if you can try this fork out and still get the perf benefits like in your PR

**Comment by ahlinc** [comment]
I've added the `postponed` tag to the original PR and asked to don't continue to push such PRs to master.

**Comment by amaanq** [comment]
I think fuzzing scala + seeing the perf benefits as before would mean it's ok :slightly_smiling_face: but yeah get_column is a bit intricate so best to be careful

**Comment by ahlinc** [comment]
> I think fuzzing scala + seeing the perf benefits as before would mean it's ok

That's not the reason, I asked to postpone it because I want to check anther solution and I don't want to make a battle of features and merge the feature that may disappear very fast if another solution would work better.

**Comment by ahelwer** [comment]
There certainly are additional places that get_column could be cached, since the parser likes to reset its position (to well-known places) quite a bit.

**Comment by dundargoc** [comment]
Does this close https://github.com/tree-sitter/tree-sitter/issues/1626?

**Comment by ObserverOfTime** [comment]
This change is binary incompatible according to `abi-compliance-checker`.

<table class="ptable"><tbody><tr>
<th class="pn"></th>
<th class="chg">Change</th>
<th>Effect</th></tr><tr>
<th>1</th>
<td>Field <b>column_cache</b> has been added at the middle position of this structural type.</td>
<td>1) Size of the inclusive type has been changed.<br>2) Layout of structure fields has been changed and therefore fields at higher positions of the structure definition may be incorrectly accessed by applications.</td>
</tr>
</tbody></table>

**Comment by maxbrunsfeld** [comment]
> This change is binary incompatible according to abi-compliance-checker.

Only changes to `api.h` affect binary compatibility. The rest of the headers are private.

**Comment by amaanq** [comment]
I've leveraged the caching in one hotspot in the parser's main lex loop when it resets to the position before the external scanner was called and noticed decent performance improvements (~7-10% in my limited testing), so I think we can land this.

**Pull request merged**
