### PR TITLE
[WIP] fix get_column side effect

### PR DESCRIPTION
**Pull request by bglgwyng**
It's a fix for #314. It's work in progress and I have some questions.

I've asked that why tree-sitter doesn't just return `extent.column` for get_column in that issue.
Now I found that `extent.column` is not the character count. It's the byte offset from the start of the row. If there's some unicode character in the text, then `extent.column` can be different from expected.

So I added `column_` to `TSPointer`.
It passed every test. But I don't think we can rely on it. Since a very rough fix(https://github.com/bglgwyng/tree-sitter/tree/7dd503cac220e5ffaac0db8ae07fdd35a42dc2ea) also passed 100%.
I guess subtree editing is not covered by tests. How can I test it then?

I didn't figure out how to fix `ts_subtree_size` in lib/src/subtree.h so I left it.
I think we need to modify `ts_subtree_new_leaf` and `ts_subtree_edit`.
Am I doing it right?

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
I don't think I want to pursue this solution, because it means a very large increase in the memory consumption of a syntax tree. Every node in the tree would need to store two additional 32-bit integers, which can add up to many megabytes in a large tree.

This is why I took the approach of computing the unicode character column count only when `get_column` is called. I think we need to understand why that code has the possibility of introducing side effects, and fix that.

**Comment by bglgwyng** [comment]
@maxbrunsfeld I remove additional unicode character count field `column_` and reimplement it following your guide.

**Comment by bglgwyng** [comment]
@maxbrunsfeld Have you checked the new commit?
The new one has very small changes from the master branch.
It just counts unicode characters from the beginning of the row using `ts_decode_utf8` or `ts_decode_utf16`.
It doesn't call `ts_lexer__advance` not to make side effects.

**Comment by maxbrunsfeld** [comment]
I can't tell why this fixes the issue; it seems like the existing implementation *should* have the same effect. The side effects are temporary, and the state should be restored by the end of the `get_column` call.

Can you add a test that reproduces the problem? I think you would need to create a minimal grammar that demonstrates the problem: something similar to [this directory](https://github.com/tree-sitter/tree-sitter/tree/master/test/fixtures/test_grammars/external_tokens).

**Comment by bglgwyng** [comment]
#589 I had posted the reproduction step here before. I should have mentioned that.
You can try `tree-sitter parse example-file-1`.
- with this fix
```
(source_file [0, 0] - [2, 1]
  (parethesized [0, 0] - [2, 1]
    (apply [0, 1] - [0, 4]
      (identifier [0, 1] - [0, 2])
      (whitespace [0, 2] - [0, 3])
      (identifier [0, 3] - [0, 4]))
    (whitespace [0, 4] - [0, 5])
    (whitespace [0, 5] - [2, 0])))
```
- with the current version
```
(source_file [0, 0] - [4, 1]
  (parethesized [0, 0] - [4, 1]
    (apply [0, 1] - [0, 4]
      (identifier [0, 1] - [0, 2])
      (whitespace [0, 2] - [0, 3])
      (identifier [0, 3] - [0, 4]))
    (whitespace [0, 4] - [0, 5])
    (whitespace [2, 3] - [4, 0])))
```
The last row number is different.

I just checked the current test suits and I found that `corpus.txt` does not contain row number and columnnumber for each token. Without them, I think I can't inspect the side effect of `get_column`. Is there any way to make test suits to tell if row number and column number are correct?

**Pull request closed without merging**
