### PR TITLE
docs: clean up binding & parser lists

### PR DESCRIPTION
**Pull request by ObserverOfTime**
- Separate official and third-party bindings
- Remove links to outdated bindings
- Move parser list to the wiki

---

We can more or less copy the list from [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/wiki/List-of-parsers).

### CODE REVIEW

**Comment by sogaiu** [comment]
For some of the PRs that requested addition (e.g. [prolog, etc.](https://github.com/tree-sitter/tree-sitter/pull/3435/files)), should these be mentioned at matrix / discord for addition to the nvim-treesitter list (those that aren't there already)?

**Comment by ObserverOfTime** [comment]
If we do move forward with this then all the open PRs will be added to the wiki here.
The nvim-treesitter page will likely be removed.

**Comment by clason** [comment]
Feel free to steal more info from the nvim-treesitter wiki (like the expanded links for parser writing resources).

**Comment by clason** [comment]
You should then also add a note how someone would get their shiny new parser into that list (ask on Discord?)

**Comment by ObserverOfTime** [comment]
> Feel free to steal more info from the nvim-treesitter wiki (like the expanded links for parser writing resources).

Those can be added to the [useful external resources](https://github.com/tree-sitter/tree-sitter/wiki/Useful-external-resources) page.
_Should we link to it somewhere in the docs?_

> You should then also add a note how someone would get their shiny new parser into that list (ask on Discord?)

Yes that will be in the wiki page.

**Pull request merged**
