### PR TITLE
StreamingIterator impl for QueryMatches in Rust Bindings

### PR DESCRIPTION
**Pull request by pr0me**
This PR addresses issues with `QueryMatches`' existing iterator.
**Problem**: Using `.next()` and related methods such as `.collect()` would potentially yield incorrect results / nodes.

**Root cause**: Each call to .next() on the iterator updates the state of underlying object in the C library.
This has the problem that if you collect a `QueryMatches`, the earlier match's captures will be overwritten by later ones, leading to Undefined Behavior.

This problem was discussed in the following issues:
https://github.com/tree-sitter/tree-sitter/issues/608
https://github.com/tree-sitter/tree-sitter/issues/2265
https://github.com/tree-sitter/tree-sitter/issues/2843
https://github.com/tree-sitter/tree-sitter/issues/2847
https://github.com/tree-sitter/tree-sitter/issues/3503

One repeatedly proposed solution to this problem was the use of a streaming iterator, correctly yielding references to `QueryMatch`es instead of copies with undefined internal states.

The old, unsafe implementation of `Iterator` for `QueryMatches` was removed.

The new `StreamingIterator` can, e.g., be used as follows:
```rust
use tree_sitter::{Node, QueryMatch};
use streaming_iterator::StreamingIterator;

let mut query_matches = query_cursor.matches(&ts_func_query, root_node, code.as_bytes());
let mut matches: Vec<Node> = Vec::new();
while let Some(m) = query_matches.next() {
    matches.push(m.captures[0].node);
    println!("{:?}", m);
}
```
Things to note:
- `for` loops do not work with streaming iterators afaik
- we cannot simply collect all `QueryMatch`es into a vector as that would require `Clone`. Instead, we can collect those parts of a Match we are actually interested in

### CODE REVIEW

**Comment by pr0me** [comment]
fixing tests

**Comment by pr0me** [comment]
fixed issues and ran tests locally.
except for these three tests, which I'm not sure correlate to my changes, everything completed successfully:
```
failures:
    tests::corpus_test::test_feature_corpus_files
    tests::node_test::test_node_is_named_but_aliased_as_anonymous
    tests::parser_test::test_parsing_after_editing_tree_that_depends_on_column_values
```

The biggest changes required were due to `StreamingIterator` having no `collect` method.
We could implement it with an extended trait but it would require to introduce `Clone` to `QueryMatch` which we might not want.  
For now, I'd advise against it and simply use the slightly more verbose syntax to work with the `StreamingIterator`.

**Comment by pr0me** [comment]
fixed wasm tests and merged recent commits from master:

> `cargo test`
> `cargo test --features=wasm`
> `script/test`
> `script/test-wasm`

all finish successfully locally.

**Comment by pr0me** [comment]
bump

merged most recent commits and successfully ran tests locally again

**Comment by pr0me** [comment]
failing check is a lint in a file my commits did not touch.

how is this handled? should I just resolve this on my branch? how are other PRs getting merged with this being present? maybe I'm missing something, sorry

**Comment by pr0me** [comment]
merged with upstream and fixed linting errors.
successfully reran all tests locally + `cargo clippy --workspace --all-targets -- -D warnings`

@amaanq if you have any opinions, suggestions or requests on this PR I'd appreciate it :)
I just think this is a pretty serious issue that was prevalent for way too long and would love to see it fixed.

**Comment by pr0me** [comment]
bump 
@ObserverOfTime maybe you can help.
any feedback on this, anything you need from me?
would love to see this merged soon.

thanks

**Comment by amaanq** [comment]
Yeah I know I hadn't said anything in a while, but I refrained from touching this because it wasn't a trivial merge - there was a lot of stuff missing, e.g. `StreamingIterator` wasn't even implemented on `QueryCaptures`, and implementing it there brought in a whole slew of issues elsewhere in the highlight crate and others (we **really** need to decouple the highlight and tags crates).

**Comment by pr0me** [comment]
agreed, not trivial.
this was my first PR to this project so I expected that there were code sites needing modifications that I would've had missed, that's why I asked for feedback, would've been happy to help :)

anyways, thanks for your work on this and the merge!

**Comment by sminez** [comment]
I've just been trying to work with this for implementing parsing and highlighting in a text editor I'm writing and it caught me out that I need to add another dependency in order to be able to make use of the return type from `QueryCursor::matches`. Is it possible to re-export the `StreamingIterator` trait from this crate at all? Or at the very least, document that you need to add the dependency for the return type of `matches` to be at all useful.

**Comment by woodruffw** [comment]
Yeah, documenting this somewhere would be really helpful -- I ran into the same issue as @sminez, where a routine bump of tree-sitter now requires a third-party trait that isn't re-exported.

**Comment by maxbrunsfeld** [comment]
We should re-export it I guess. Or make the methods also available as inherent methods, in addition to the trait impl.

**Pull request merged**
