### PR TITLE
Add the link of csharp binding to the doc

### PR DESCRIPTION
**Pull request by DennySun2100**

### CODE REVIEW

**Comment by DennySun2020** [comment]
Hi @amaanq, could you help merge this since I have no write access

**Comment by amaanq** [comment]
Yeah doc link updates are done in batches sporadically - I think maybe we can do one soon w/ this (see all the PRs w/ the label doc-link)

**Comment by DennySun2020** [comment]
Just a reminder, do you have a plan for the next updates on the doc?

**Comment by amaanq** [comment]
Superseded by #2881, thank you!

**Pull request closed without merging**
