### PR TITLE
store ref of parent in subtree

### PR DESCRIPTION
**Pull request by lewis6991**
Goal is to re-implement `ts_node_parent()` so it is more efficient.

Might not be possible.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
We can't do this because subtrees can be reused in multiple parents when doing incremental parsing.

**Comment by lewis6991** [comment]
Damm, that's a real shame. Currently, traversing up a tree is really expensive since you have to search for a node from a root each time.

For context, the main usecase that is the motivation here is to efficiently build a list of a nodes ancestors. Current attempts use `ts_node_parent()` or `ts_node_containing_descendant()` in a loop, but I don't think either of these scale well for very large files since they both involve a lot of searching for a node descendant.

> subtrees can be reused in multiple parents when doing incremental parsing.

I assume this implies a constraint any old trees must remain valid after any incremental parse, i.e. it's not possible to just maintain a pointer to the most up-to-date parent?

**Comment by maxbrunsfeld** [comment]
Yeah. I've thought about removing the `ts_node_parent` function entirely, since the TreeCursor is the main API that is designed to efficiently traverse a tree more than just downwards.

**Comment by lewis6991** [comment]
For other reasons, the tree cursor API isn't particularly ideal since you still need to search from the root of the tree, but at least it is able to re-use the work it has done from what I understand.

**Comment by lewis6991** [comment]
See #3716 which shows that using the public tree cursor API to get a nodes descendants is magnitudes slower than any other method.

**Pull request closed without merging**
