### PR TITLE
Pin emscripten/emsdk Docker version

### LINKED ISSUE #1178: `scripts/build-wasm --docker` fails
```console
$ script/build-wasm --docker
which: no emcc in (/home/vladimir/bin/home:/home/vladimir/bin/private:/home/vladimir/bin:/home/vladimir/opt/adt/sdk/tools:/home/vladimir/opt/adt/sdk/tools/bin:/home/vladimir/perl5/bin:/home/vladimir/.npm-packages/bin:/home/vladimir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/vladimir/.gem/ruby/3.0.0/bin:/usr/bin/core_perl:/usr/bin/vendor_perl:/home/vladimir/.cargo/bin:/home/vladimir/work/extern/go/bin:/home/vladimir/.dotnet/tools)
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libGL.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libGL.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libal.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libal.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libhtml5.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libhtml5.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libsockets.a... (this will be cached in "/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libsockets.a" for subsequent builds)
cache:INFO:  - ok
emcc: error: undefined exported symbol: "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_" [-Wundefined] [-Werror]
```

### PR DESCRIPTION
**Pull request by CyberShadow**
Fixes issues caused by incompatible changes in Emscripten since the time that tree-sitter was built.

This fixes #1178, #1179, and possibly should permanently fix other related issues such as #1095, provided that `--docker` is used.

### CODE REVIEW

**Comment by CyberShadow** [comment]
@maxbrunsfeld To give a bit more context on this. Currently, to build a WASM parser binary that will work against a specific build of tree-sitter, two things must match: the tree-sitter ABI version and the emscripten version. By pinning the emscripten version, we tie the emscripten version to the tree-sitter version, therefore only requiring that users match the tree-sitter version (at least when building with --docker).

The emscripten version can then be periodically bumped to the latest version to pull in the latest emscripten improvements.

**Review by maxbrunsfeld — COMMENTED** [review]
Thanks, this change makes sense.

Could we keep these three version numbers in sync by sharing a common `EMSCRIPTEN_VERSION` file in the repository, and loading/including that file in these three places?

Also, should we pick the very latest version (2.0.24), or do you know of any concerns with recent versions?

**Comment by CyberShadow** [comment]
> Could we keep these three version numbers in sync by sharing a common `EMSCRIPTEN_VERSION` file in the repository, and loading/including that file in these three places?

I think so. But, I don't think it's possible to do that for the GitHub Actions workflow, as the version there is passed as a parameter to the `mymindstorm/setup-emsdk` version. So, there would either have to be at least two places which mention the version, or the respective components will have to parse/grep `ci.yml`.

> Also, should we pick the very latest version (2.0.24), or do you know of any concerns with recent versions?

I used the version from the GitHub workflow so that the output will match CI builds. I don't know of any reason not to bump it, other than separation of concerns.

**Comment by maxbrunsfeld** [comment]
Here's the recommended way to set an environment variable dynamically on GH actions:

```
echo "{name}={value}" >> $GITHUB_ENV
```

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable.

**Comment by CyberShadow** [comment]
`mymindstorm/setup-emsdk` seems to fail to install the latest version (2.0.24). I don't understand why.

I suggest doing the version bump in another PR, to also address @ahlinc's exports update there.

**Comment by ahlinc** [comment]
@CyberShadow I'm not sure, try to update `mymindstorm/setup-emsdk` own version like `mymindstorm/setup-emsdk@v10` which is latest.

**Comment by ahlinc** [comment]
@CyberShadow @maxbrunsfeld I've tested suggested above fix for CI and Emscripten, it works fine: https://github.com/ahlinc/tree-sitter/runs/2946922253?check_suite_focus=true#step:8:54

**Comment by ahlinc** [comment]
@maxbrunsfeld Suggested fixes works fine, so I've made another PR #1219 where added my suggested fixes.

**Comment by CyberShadow** [comment]
@maxbrunsfeld If possible, I would like to nominate @ahlinc (if they're interested) as co-maintainer. They seem to have been around for some time, are active in discussions and new issues, and generally seem to have a good handle of what's going on. :)

**Comment by maxbrunsfeld** [comment]
Yeah, @ahlinc has been doing amazing work on Tree-sitter. His careful debugging, and great detailed technical explanations have been a great asset to the project, and extremely helpful to a lot of folks who've been asking questions on GitHub.

@ahlinc, since I don't have an email address to contact you at, this seems like as good a place as any to ask you: are you interested in having commit access to this repository, and having  your name listed somewhere as an official maintainer? The only expectation would be to keep doing what you're already doing, but in certain cases I think it makes sense for you to be able to merge PRs yourself. Feel free to email me at my email address listed on my GitHub profile if you'd like to talk more about it.

/cc @dcreager for visibility, since you've been my primary point of contract regarding Tree-sitter at GitHub.

**Comment by dcreager** [comment]
I'm :+1: to this, @ahlinc has been crushing it

**Comment by ahlinc** [comment]
@CyberShadow Thank you for your proposal and @dcreager for supporting it :raised_hands:.

@maxbrunsfeld I'm very interested to be more involved in the tree-sitter improving process. I'll send you an email. :slightly_smiling_face:

**Pull request merged**
