### PR TITLE
Add Noir tree-sitter-grammar to Docs

### PR DESCRIPTION
**Pull request by hhamud**
* Added a link to the newly created [grammar](https://github.com/hhamud/tree-sitter-noir) of the [noir language](https://noir-lang.org/) to the doc site

### CODE REVIEW

**Comment by hhamud** [comment]
This has been hanging here for awhile, its a very small change and needs minimal oversight.

Can we merge this in please?.

**Comment by ahlinc** [comment]
I do such doc link merges as one a batch merge from time to time.

**Comment by sogaiu** [comment]
FWIW, I have [a gist](https://gist.github.com/sogaiu/a5527eac95a070823408a7fd8fc690e9) that has content from multiple PRs of this sort assimilated.

At the bottom is a listing of which PRs were accounted for.

**Comment by hhamud** [comment]
> FWIW, I have [a gist](https://gist.github.com/sogaiu/a5527eac95a070823408a7fd8fc690e9) that has content from multiple PRs of this sort assimilated.
> 
> At the bottom is [a listing of which PRs were accounted for](https://gist.github.com/sogaiu/a5527eac95a070823408a7fd8fc690e9#file-which-prs-md).

Nice, I had no idea that you were doing this but most people would rely on the main website to check to see if there even exists a treesit package for their language.

**Comment by sogaiu** [comment]
Sure, the gist was intended just as preliminary work to aid maintainers.

If you'd like to see a longer list, there is [this](https://github.com/sogaiu/ts-questions/blob/master/ts-grammar-repositories.txt) too.

**Comment by amaanq** [comment]
Superseded by #2881, thank you!

**Pull request closed without merging**
