### PR TITLE
Linting, Formatting, & Tidying

### PR DESCRIPTION
**Pull request by amaanq**
This PR ~tidies up the ci scripts,~ fixes a few warnings/clippy lints in the autogenerated Rust bindings, and applies clippy lints throughout the project where I found reasonable and useful.

### CODE REVIEW

**Comment by ahlinc** [comment]
@amaanq thank you for the efforts! :1st_place_medal: Overall there are a lot of changes that should be applied for sure but I don't agree with all changes especially in CICD and with other changes that aren't related to `clippy` suggestions, I'll review and revert things with what I'm not agree to cleanup this PR and prepare it to be merged.

**Comment by amaanq** [comment]
rebased

**Comment by Harrypotter19876** [comment]
package]]
name = "tree-sitter-cli"
version = "0.18.2"
version = "0.18.3"
dependencies = [
 "ansi_term",
 "atty",

**Comment by ahlinc** [comment]
Lets postpone this for the next week, currently there are other more valuable things exist.

**Comment by ahlinc** [comment]
Please don't merge this, I plan to reorganize it completely.

**Comment by amaanq** [comment]
Windows CI failure fixed :innocent:

**Pull request closed without merging**
