### PR TITLE
Adding API to get field name of a TSNode

### PR DESCRIPTION
**Pull request by nhasabni**
This PR adds an API to get name of the field of TSNode's child.
It uses same set of arguments as that of ts_node_child, but returns
field name if it is found, otherwise it returns NULL.

This API is useful to implement custom printing of S-expressions such
as following:

"(binary_expression
   (binary_expression_left (identifier))
   (binary_expression_operator ("+"))
   (binary_expression_right (identifier)
)"

Currently, ts_node_string does not allow any customization for printing.
This PR addresses question #1090.

### CODE REVIEW

**Comment by nhasabni** [comment]
Hello, this PR addresses question #1090.

**Review by maxbrunsfeld — COMMENTED** [review]
I'm open to this addition. There's two changes I'd suggest:

* Could you rename it to `ts_node_field_name_for_child`?
* Can you add a unit test for the new function in [this file](https://github.com/tree-sitter/tree-sitter/blob/b8ff6447d7041d198e94c2600a65c10300ddadde/cli/src/tests/node_test.rs#L229)? You'll need to add a Rust binding around [here](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_rust/lib.rs#L858), which will require running the [`generate-bindings`](https://github.com/tree-sitter/tree-sitter/blob/master/script/generate-bindings) script.

**Comment by nhasabni** [comment]
@maxbrunsfeld Thanks for your comments. I've addressed your comments. Please take a look.

**Comment by maxbrunsfeld** [comment]
Thanks!

**Pull request merged**
