### PR TITLE
feat(docs): mention how to use dsl.ts + node types

### PR DESCRIPTION
**Pull request by sigmaSd**
fix https://github.com/tree-sitter/tree-sitter/issues/2505

### CODE REVIEW

**Comment by ahlinc** [comment]
As I said in  https://github.com/tree-sitter/tree-sitter/issues/2505#issuecomment-1679823244 this would be managed automatically for all new grammars.

**Comment by sigmaSd** [comment]
Ah I see what you mean now

what about adding this part `npm install --save-dev tree-sitter-cli @types/node`  ?

**Comment by sigmaSd** [comment]
Also that pr seems to be taking time, its not a bad idea to add improve the docs until it lands

**Comment by ahlinc** [comment]
Could you tell for what purpose you want to install `@types/node` node types? We're moving to make Tree-sitter and its grammars having minimum dependencies.

**Comment by amaanq** [comment]
Yeah you don't need that, just referencing the dsl works like so
```js
/// <reference types="tree-sitter-cli/dsl" />
```

**Comment by sigmaSd** [comment]
here is how it looks without @types/node
image

**Comment by amaanq** [comment]
Weird, is that from tsserver? I forgot to mention adding ts-check below the reference gets you what you need

```js
// @ts-check
```

**Comment by sigmaSd** [comment]
yes that's from tsserver, and adding ts-check doesn't change the error

**Comment by amaanq** [comment]
Weird, I don't get the message you have, would be interesting if you have more context/info about your setup

**Comment by sigmaSd** [comment]
I' m using helix with tsserver lsp 

I tried vscode, if I only mention module I get the same error 
image


But if I assign module to something the error disappear

If I'm going to start guessing ,maybe vscode is doing extra heuristics that the tsserver lsp can't do, I'm assuming you're using vscode ?

image

**Comment by amaanq** [comment]
I'm using neovim w/ tsserver

**Comment by sigmaSd** [comment]
I get the same behavior as vscode with neovim

So I guess I'll debug this on helix side, you can ignore this problem for now

**Comment by sigmaSd** [comment]
in other words @types/node should be not needed indeed

**Comment by sigmaSd** [comment]
helix seems to typecheck by default and in strict mode

neovim and vscode just ignore the error, and there is no typings for module, the only way to correctly fix this is to install node types

Either way its no big deal, and if something gets bothered I'm guess they will find this issue

**Pull request closed without merging**
