### PR TITLE
Make it clearer in README.md where to find docs for building

### PR DESCRIPTION
**Pull request by mgsloan**

### CODE REVIEW

**Comment by ret394** [comment]
👍

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by mgsloan** [comment]
I've rebased this atop latest master

**Review by aminya — APPROVED** [review]

**Review by aminya — APPROVED** [review]
Yes, I did have some trouble jumping between different links to find the related documentation.

**Comment by ahlinc** [comment]
There is a `CONTRIBUTING.md` in the repo root and a separate clear section in a left side menu of the docs, I think it's enough points.

**Pull request closed without merging**
