### PR TITLE
Fix get_column() segfault on EOF, don't do lookahead without EOF check first

### LINKED ISSUE #2039: `get_column` segfaults on EOF
See also https://github.com/nvim-treesitter/nvim-treesitter/issues/4170

## steps

Inside an external scanner call `get_column` on EOF.

## problem

```
Thread 1 "nvim" received signal SIGSEGV, Segmentation fault.
0x000055f4499d4a32 in ts_decode_utf8 ()

(gdb) bt 100
#0  0x000055f4499d4a32 in ts_decode_utf8 ()
#1  0x000055f4499d4c47 in ts_lexer.get_lookahead ()
#2  0x000055f4499d4fd2 in ts_lexer.get_column ()
#3  0x00007eff09d10a8a in tree_sitter_scala_external_scanner_scan ()
   from /home/eed3si9n/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/scala.so
#4  0x000055f4499bad11 in ts_parser_parse ()
#5  0x000055f4497789b1 in parser_parse (L=0x7eff0b28a380) at /home/eed3si9n/work/neovim/src/nvim/lua/treesitter.c:416
#6  0x000055f4499f5246 in lj_BC_FUNCC ()
#7  0x000055f4499e15ac in lua_pcall (L=0x7eff0b28a380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at lj_api.c:1116
#8  0x000055f4497701bf in nlua_pcall (lstate=0x7eff0b28a380, nargs=2, nresults=1) at /home/eed3si9n/work/neovim/src/nvim/lua/executor.c:140
#9  0x000055f449773cdd in nlua_call_ref (ref=16, name=0x55f449a5622b "buf", args=..., retval=true, err=0x7ffda322a8f0)
    at /home/eed3si9n/work/neovim/src/nvim/lua/executor.c:1518
#10 0x000055f449664a60 in decor_provider_invoke (ns_id=1, name=0x55f449a5622b "buf", ref=16, args=..., default_true=true,
    perr=0x55f449b6ef78 <provider_err>) at /home/eed3si9n/work/neovim/src/nvim/decoration_provider.c:27
#11 0x000055f449665a82 in decor_providers_invoke_buf (buf=0x55f44b756670, providers=0x7ffda322aa60, err=0x55f449b6ef78 <provider_err>)
    at /home/eed3si9n/work/neovim/src/nvim/decoration_provider.c:175
#12 0x000055f44967797c in update_screen (type=10) at /home/eed3si9n/work/neovim/src/nvim/drawscreen.c:626
#13 0x000055f44967ea5a in ins_redraw (ready=true) at /home/eed3si9n/work/neovim/src/nvim/edit.c:1357
#14 0x000055f44967ce52 in insert_check (state=0x7ffda322ac70) at /home/eed3si9n/work/neovim/src/nvim/edit.c:469
#15 0x000055f4498b9a56 in state_enter (s=0x7ffda322ac70) at /home/eed3si9n/work/neovim/src/nvim/state.c:30
#16 0x000055f44967ca0d in insert_enter (s=0x7ffda322ac70) at /home/eed3si9n/work/neovim/src/nvim/edit.c:331
#17 0x000055f44967e63a in edit (cmdchar=97, startln=false, count=1) at /home/eed3si9n/work/neovim/src/nvim/edit.c:1263
#18 0x000055f4497e72b0 in invoke_edit (cap=0x7ffda322ae50, repl=0, cmd=97, startln=0) at /home/eed3si9n/work/neovim/src/nvim/normal.c:7061
#19 0x000055f4497e7242 in nv_edit (cap=0x7ffda322ae50) at /home/eed3si9n/work/neovim/src/nvim/normal.c:7038
#20 0x000055f4497d9d8f in normal_execute (state=0x7ffda322add0, key=97) at /home/eed3si9n/work/neovim/src/nvim/normal.c:1172
#21 0x000055f4498b9b8b in state_enter (s=0x7ffda322add0) at /home/eed3si9n/work/neovim/src/nvim/state.c:88
#22 0x000055f4497d7f78 in normal_enter (cmdwin=false, noexmode=false) at /home/eed3si9n/work/neovim/src/nvim/normal.c:471
#23 0x000055f44977db28 in main (argc=3, argv=0x7ffda322b1c8) at /home/eed3si9n/work/neovim/src/nvim/main.c:583
```

## expectations

It doesn't crash.

### PR DESCRIPTION
**Pull request by ahlinc**
Fixes #2039

### CODE REVIEW

**Comment by ahlinc** [comment]
_Context: https://discord.com/channels/1063097320771698699/1063097321648312354/1099263997989093396_

@sogaiu was able to reproduce the bug as was described in https://github.com/tree-sitter/tree-sitter/issues/2039#issuecomment-1518546806 and after applying the patch from this PR the segfault crash is gone. _Thank you for the help and assistance!_

**Comment by sogaiu** [comment]
I had good help from @clason :)

**Comment by eed3si9n** [comment]
Thanks all!

**Comment by maxbrunsfeld** [comment]
Thanks so much everyone who worked on this.

**Pull request merged**
