### PR TITLE
JSON test report

### PR DESCRIPTION
**Pull request by kylegoetz**
Addresses #3891

More can be done. But I wanted to start the PR and get feedback.

With this PR, if one executes `git test --report` it will dump a JSON of test results to stdout instead of the default stdout formatting.

It only does corpus tests right now. The output is akin to this format:

```typescript
type TestResults = {
  "name": "corpus",
  "file_path": null,
  "children": (Group|Example)[]
}

type Group = {
  "name": string,
  "file_path": string,
  "children": (Group|Example)[]
}

type Example = {
  "name": string,
  "results": Result[],
}

type Result = {
  "name": string,
  "status": "fail",
  "actual_output" string,
  "diff": DiffLine[]
} | {
  "name": string,
  "status": "pass",
  "actual": string,
} | {
  "name": string,
  "status": "skipped"
}

type DiffLine = {
  tag: 'delete' | 'insert' | 'equal',
  value: string,
}
```

One can generate HTML from this that includes the ability to click on a test name and get directed to the file (in browser) with the name of the test centered and highlighted (but this code is currently not included in the PR; it's a Node project I haven't packed for NPM yet. It is a single HTML file that could be templated and included in TS as something like `tree-sitter test --html-report` that would take the JSON and dump it into the template and then log the template's HTML to screen.

A few screenshots, one of the JSON output, and one of a simple HTML report that could be built-in if desired:

Screenshot 2024-11-13 at 2 44 39 PM
Screenshot 2024-11-13 at 2 44 47 PM
Screenshot 2024-11-13 at 2 46 13 PM

### CODE REVIEW

**Comment by kylegoetz** [comment]
I'd wondered about how TS iterates through languages and runs the tests for each language. When I test here, the languages in the test opts has no name, and is the language I'm running the test from. But since TS iterates over the languages, that is why the JSON for Example.results is an array rather than an object.

There's also some `no_platform` code, and I wasn't sure what that is.

**Comment by kylegoetz** [comment]
The code could be simplified if the "default" way of logging tests to stdout were converted from all those println calls to an accumulator that dumps the entire thing to stdout at the end (which is what the json does). Then the two code branches (json and the "default") could be merged into a single one.

But I was loathe to make that change myself.

**Comment by amaanq** [comment]
> The code could be simplified if the "default" way of logging tests to stdout were converted from all those println calls to an accumulator that dumps the entire thing to stdout at the end (which is what the json does). Then the two code branches (json and the "default") could be merged into a single one.
>
>But I was loathe to make that change myself.

If you're willing to put in the effort, that'd be great and totally accepted, but in its current state, the delta from where this PR is at and where it'd ideally be is quite large - here are my thoughts

1. we should allow people to just output results to a JSON file, for parsing and testing - this flag would be something like `json-report`, and then it can be combined with a flag like `open-report` that is similar to `open-log` for `parse`, in which this UI to view your results shows up (something similar to clang's `scan-build` would be cool).

2. the json data **should** be typed - just spamming `json!` everywhere is very error prone

**Comment by kylegoetz** [comment]
I've got a new code branch I'm working on this. Right now passing `--report` will log a JSON object containing corpus, highlighting, and tag test results, and without it, the behavior is unchanged from current `tree-sitter test` as far as I can tell.

I wrote a lot of unit tests to nail down the behavior.

To do is create a flag to export the JSON optionally to a file and have the flag that will open it in a viewer. I prefer having the ability to dump to stdout instead of to a file because some users (this includes me) will want to pipe the JSON to a viewer instead of writing to a file and opening it with the viewer, and then needing to remember to delete that file later.

https://github.com/kylegoetz/tree-sitter/tree/feat/json

**Pull request closed without merging**
