### PR TITLE
Syntax highlighting primer from PRs

### PR DESCRIPTION
**Pull request by kramred**
A first shot to piece together the current status of the CLI highlight subcommand (but also the API) from PRs mentioning highlight that I could find - feel free to rewrite or drop whatever you see fit; there might be errors.
I'd really appreciate some more/centralized documentation on the syntax highlighting, hope this can serve as a starting point

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Hi, this documentation is something that I'm working on as we speak. 😁

Thanks for raising this as an issue and writing this up however. I most likely will not merge this PR *directly*, but will use it as a reminder of all the things that should be included in my docs, and I may take pieces of what you've done in my new docs page.

**Comment by kramred** [comment]
Thanks, that would be great. 
More documentation is always good (with examples even better, like the ones you have in some of the PRs)

**Comment by maxbrunsfeld** [comment]
Ok, the syntax highlighting docs are up: http://tree-sitter.github.io/tree-sitter/syntax-highlighting.

I'm going to close this one out since I think that page covers this stuff. If you spot things that are missing, and you think ought to be in the docs, please let me know.

**Comment by kramred** [comment]
Just read it and it looks good. Will give it a second, more detailed, read the next days.
Thanks for including highlighting in the docs!

**Pull request closed without merging**
