### PR TITLE
cli test: use diff format for expected vs actual

### LINKED ISSUE #655: Pretty print test output
When receiving a mismatch between the expected and actual AST  it is not formatted in a readable way. instead it is all on one line.

It would be nice if it was printed in a more readable format. I try to use the tests as a feed backloop while developing the parser and they are just not readable enough for that.

### PR DESCRIPTION
**Pull request by milahu**
fix #655 and #823 

#823 - use better diff algorithm  
the old library sometimes fails to find the longest common sequence (LCS)

#655 - prettify output

old format

<tt>1 failure:</tt>

<tt><span color="green">expected</span> / <span color="red">actual</span></tt>

<tt>1. Name of test</tt>

<tt>(component (element (start_tag (tag_name)) (text) (element (start_tag (tag_name)) (text) <span color="red">(text_expression</span> <span color="green">(expression</span> (raw_text)) (end_tag (tag_name))) (text) (element (start_tag (tag_name) (directive_attribute (directive_name))) (text) <span color="red">(text_expression</span> <span color="green">(expression</span> (raw_text)) (end_tag (tag_name))) (text) (end_tag (tag_name))))</span></tt>

new format

```diff
1 failure:

1. Name of test

+++ expected
--- actual
  (component (element (start_tag (tag_name)) (text) (element (start_tag (tag_name)) (text)
+ (expression
- (text_expression
  (raw_text)) (end_tag (tag_name))) (text) (element (start_tag (tag_name) (directive_attribute (directive_name))) (text)
+ (expression
- (text_expression
  (raw_text)) (end_tag (tag_name))) (text) (end_tag (tag_name))))
```

benefit: compatibility with GNU diff, simply copy-paste to markdown <tt>```diff</tt>

cost: test output cannot be indented

alternative: produce html code to encode colors

todo
* allow to disable colors via CLI, similar to `diff --color=never`
* auto-indent the ascii tree
* find a better algorithm than myers algorithm, to avoid 'sliding errors' (patience diff or histogram diff), compare trees not strings

tree diff:
expected
```diff
  (fragment (element (self_closing_tag (tag_name)))
+ (text)
  )
```
actual
```diff
  (fragment (element (self_closing_tag
+ (tag_name))) (text))
- (tag_name))))
```

### CODE REVIEW

**Comment by milahu** [comment]
demo of current version

<pre>
  ✗ <span color="red">test demo</span>

1 failure:

  1. test demo:

<span color="green">+++ expected</span>
<span color="red">--- actual</span>
  component 1:0 <span color="grey"></span>&lt;template&gt;\n  &lt;div&gt;\n    &lt;span&gt;hello&lt;/span&gt;\n  &lt;/div&gt;\n&lt;/template&gt;\n<span color="grey"></span>
    template_element 1:0 <span color="grey"></span>&lt;template&gt;\n  &lt;div&gt;\n    &lt;span&gt;hello&lt;/span&gt;\n  &lt;/div&gt;\n&lt;/template&gt;<span color="grey"></span>
      start_tag 1:0 <span color="grey"></span>&lt;template&gt;<span color="grey"></span>
        tag_name 1:1 <span color="grey"></span>template<span color="grey"></span>
      text 1:10 <span color="grey"></span>\n<span color="grey">  </span>
      element 2:2 <span color="grey"></span>&lt;div&gt;\n    &lt;span&gt;hello&lt;/span&gt;\n  &lt;/div&gt;<span color="grey"></span>
        start_tag 2:2 <span color="grey"></span>&lt;div&gt;<span color="grey"></span>
          tag_name 2:3 <span color="grey"></span>div<span color="grey"></span>
<span color="red">-       text</span> 2:7 <span color="grey"></span>\n<span color="grey">    </span>
<span color="red">-       element</span> 3:4 <span color="grey"></span>&lt;span&gt;hello&lt;/span&gt;<span color="grey"></span>
<span color="red">-         start_tag</span> 3:4 <span color="grey"></span>&lt;span&gt;<span color="grey"></span>
<span color="red">-           tag_name</span> 3:5 <span color="grey"></span>span<span color="grey"></span>
          text 3:10 <span color="grey"></span>hello<span color="grey"></span>
          end_tag 3:15 <span color="grey"></span>&lt;/span&gt;<span color="grey"></span>
            tag_name 3:17 <span color="grey"></span>span<span color="grey"></span>
        text 3:22 <span color="grey"></span>\n<span color="grey">  </span>
<span color="green">+       comment
+       text
+       element
+         start_tag
+           tag_name</span>
<span color="red">-       end_tag</span> 4:2 <span color="grey"></span>&lt;/div&gt;<span color="grey"></span>
<span color="red">-         tag_name</span> 4:4 <span color="grey"></span>div<span color="grey"></span>
<span color="red">-     text</span> 4:8 <span color="grey"></span>\n<span color="grey"></span>
<span color="red">-     end_tag</span> 5:0 <span color="grey"></span>&lt;/template&gt;<span color="grey"></span>
<span color="red">-       tag_name</span> 5:2 <span color="grey"></span>template<span color="grey"></span>
</pre>

terminal colors converted to html with the [aha](https://github.com/milahu/random/blob/master/colors-to-github.sh) tool
limitation: we can not set background color like
<code>&lt;span color="darkgrey" background="lightgrey"&gt;fail&lt;/span&gt;</code>

all non-printable characters are escaped, also `\t`

line- and column-numbers are printed for every actual node

in the terminal, leading and trailing spaces are printed as grey blocks



trailing spaces are visible in markdown-diff:
here are four spaces after `\n`

```diff
          tag_name 2:3 div
-       text 2:7 \n    
```

**Comment by Mayank-1234-cmd** [comment]
<span color="red">test colors</span>

**Comment by dundargoc** [comment]
Wanna rebase this?

**Comment by milahu** [comment]
nope, sorry

**Comment by dundargoc** [comment]
I think it makes the most sense to close this then. The work done here is still available if anyone wants to make use of it.

**Comment by amaanq** [comment]
sorry for not getting to this sooner @milahu, but I'll probably build on this with some other functionality in the near future. thank you!

**Pull request closed without merging**
