### PR TITLE
Modify styles to show icon for external links

### PR DESCRIPTION
**Pull request by kramred**
Hello,

this is purely a question of personal preference/taste. I've added a style and an icon to indicate which hyperlinks are external. Icon is [CC0](https://wiki.creativecommons.org/wiki/CC0), created by me.

Feel free to use or drop.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Interesting, can you post a screenshot of what this looks like on one of the docs pages?

**Comment by kramred** [comment]
Screen-shot with the other PR combined for adding the github link:
127 0 0 1_4000_(Laptop with MDPI screen) (1)

**Comment by maxbrunsfeld** [comment]
Nice!

**Comment by danlamanna** [comment]
Newcomer to tree-sitter and I came looking for this because I found this behavior quite confusing. I've never seen this icon used to denote anything about the _destination_ of the link. This icon is typically used as an indicator of the _behavior_ of opening the link, which is almost always in a new tab. See [open in new tab icon](https://www.google.com/search?q=open+in+new+tab+icon) for instance.

**Comment by danlamanna** [comment]
Okay, apparently I don't know how the internet works. TIL this is a thing. Please ignore.

**Pull request merged**
