### PR TITLE
Improvement for PR #1180 Emscripten version 2.0.24

### LINKED ISSUE #1131: WASM library fails to build with emscripten 2.0.23, 2.0.24
Running `./script/build-wasm` from the tree-sitter 0.19.5 tarball with emscripten 2.0.23 produces the following error:

```
emcc: error: undefined exported symbol: "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_" [-Wundefined] [-Werror]
```

This occurs on macOS Mojave (10.14.6), Catalina (10.15.7) and Big Sur (11.3.1, both Intel and ARM). See https://github.com/Homebrew/homebrew-core/pull/78307.

Build logs available at https://github.com/Homebrew/homebrew-core/actions/runs/887494523. The error on Intel Big Sur starts at https://github.com/Homebrew/homebrew-core/runs/2699349013?check_suite_focus=true#step:7:62.

### PR DESCRIPTION
**Pull request by ahlinc**
This PR continues #1180 and resolves an issue with CI to build all for the latest Emscripten 2.0.24.
Closes  #1131

### CODE REVIEW

**Comment by CyberShadow** [comment]
@ahlinc  Uh oh. I'm getting `function signature mismatch` with this again.

**Comment by CyberShadow** [comment]
Sorry, false alarm, forgot to run `script/build-wasm --docker`.

**Comment by ahlinc** [comment]
@CyberShadow Hmm, could you get a link to some code where it happens? And describe how to reproduce?

**Comment by CyberShadow** [comment]
@ahlinc Sorry, false alarm, forgot to run `script/build-wasm --docker`. :)

**Pull request merged**
