### PR TITLE
chore: document preferred language for scanner

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This documents that C is the preferred language for external scanners as mentioned in https://github.com/tree-sitter/tree-sitter/pull/2897#issuecomment-1928112073

Thanks!

### CODE REVIEW

**Comment by amaanq** [comment]
We might even consider removing c++ support, it's just not needed.

**Comment by calebdw** [comment]
I'm fine with that, I can update the docs if you want.

**Comment by sogaiu** [comment]
@amaanq I guess you'd know pretty well about how much C++ use there is in practice given how much rewriting you've done.

Should I check via ts-questions for any remaining `scanner.cc` files?

**Comment by amaanq** [comment]
yeah sure I'll check as well and rewrite any that seem to have some sizable usage/relevance, I've just finished rewriting Ruby (last upstream one in c++ that I didn't bother to touch :laughing:)

**Comment by sogaiu** [comment]
Some rough results of find | grep | sort | uniq | wc -l:

* `grammar.js`: 423
* `scanner.c`: 149
* `scanner.cc`: 31

Number of repositories: 406

**Comment by amaanq** [comment]
A few of those I already sent PRs to rewrite and either the owner just didn't respond or didn't want it (astro, beancount) :shrug: 
Ikatyang also looks to be very inactive (yaml/vue) :grimacing:

**Comment by amaanq** [comment]
Merging for now then I think we can remove C++ support in a month or two

**Pull request merged**
