### PR TITLE
Add a changelog Markdown file.

### PR DESCRIPTION
**Pull request by azizk**
Hi!

Right now it's difficult to keep track of the changes and the progress in the project. Can I suggest to add a changelog file?

I just added an example file. Feel free to change it.

Awesome project, btw! :+1:

### CODE REVIEW

**Comment by ahlinc** [comment]
Duplicates: #527, #1031 there are plans for this in #930.
@azizk I would close the PR that doesn't suggest a good maximally automated solution that would require just minor cosmetic changes in the changelog before release. Such solution should be somehow integrated with Git and it's abilities for retrieve a bunch  of commits from the last released tag. I know many git-based changelog generators in the field but all of them have own issues and that's the reason why such solution wasn't proposed yet.

**Comment by azizk** [comment]
Oh yeah, I read that checklist a while ago. I think it's great info, but a changelog is more about the recent changes and progress made between releases. Of course, you can look at the commit history, but that is just too much information. It might be a chore to maintain a changelog but I think its importance is high enough to do it without using subpar automated solutions. It's a way to communicate to outsiders of the project what's been happening and what (exciting things!) they can expect from updates. Among the outsiders are language grammar writers and those who want to become one, or developers who're trying to integrate tree-sitter with an editor. It's pretty useful information in my opinion.

PS: Sorry about missing the previous issues. I thought I did a search beforehand.

**Comment by azizk** [comment]
By the way, I think it would be great to have Max's checklist in a BACKLOG.md file to make it more visible. :+1:

**Comment by ahlinc** [comment]
Starting from [v0.20.8](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.8) I've started to maintain description for releases _(thanks for Github automation)_. The changelog file will be added in the future.

As for now I close this PR for reasons:
* Changelog addition is on plans and all maintainers remember about it.
* There are release descriptions that will be for every version and will be in sync with the changelog file in the future.
* Trying to cleanup abandoned PRs and issues to simplify maintainers work.

**Pull request closed without merging**
