### PR TITLE
Add .firstChildForIndex and .firstNamedChildForIndex to wasm bindings

### PR DESCRIPTION
**Pull request by Razzeee**
This needs testing, but I'm not sure how to do that.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Just curious - are you using these methods for anything? I don't think they're used anymore in Atom and I wasn't sure if it was still worth having them.

**Comment by Razzeee** [comment]
No, I'm not using them. The only one that's missing, that I'm using is `.descendantsOfType`

Just thought somebody else might profit. 

I'm also not using the `.closest` method that's also missing from the wasm bindings, but maybe due to the fact, that these are not documented and it's not clear what it does?

**Comment by maxbrunsfeld** [comment]
I actually don't think these methods need to exist any more. Thanks for diving into this code anyways.

**Comment by Razzeee** [comment]
Would be cool, if you can drop the `closest` tests then, just in case somebody else stumbles over that?

**Comment by maxbrunsfeld** [comment]
I'll implement `closest` at some point, so I think I'll keep those tests around.

**Pull request closed without merging**
