### PR TITLE
feat: non-breaking include/exclude regex options for subcommand test 

### PR DESCRIPTION
**Pull request by buckynbrocko**
cli `tree-sitter test`:
- Added `-i`/`--include` optional argument to run only tests whose names match the given regex string
- Added `-e`/`--exclude` optional argument to run only tests whose names _do not_ match the given regex string

This is notably different from #2875 [Allow _--filter_ to take regex](https://github.com/tree-sitter/tree-sitter/pull/2875) and #2635 [feature: add --exclude to tree-sitter-test](https://github.com/tree-sitter/tree-sitter/issues/2635)
in that it leaves the current `-f`/`--filter` option as-is to prevent a breaking change as well as allow it to be deprecated at a later time (if ever) after a suitable warning period. It may be a good idea to make `filter` conflict with `include` (or both) to prevent confusion/misuse, but that can be decided later.

Examples
```shell
tree-sitter test --include "(?i)statements?" # run only tests with `statement(s)` in their name, case insensitive
tree-sitter test --exclude "Identifier$" # run only tests whose name doesn't end with `Identifier`
tree-sitter test --include "(?i)statements?" --exclude "Identifier$" # include && exclude
```

### CODE REVIEW

**Comment by amaanq** [comment]
I think we can remove filter, and keep these two. It's definitely useful to just use a regex, and having too many flags gets annoying.

**Comment by sogaiu** [comment]
Is it that bad to have at least one release where the old option coexists with the new ones?  Seems kinder from a breakage perspective.

Just my two cents.

**Comment by amaanq** [comment]
Hm, maybe. Though 0.20.9 has filter, since it doesn't have these users might be bit by it. Let's keep it for 0.20.10 then remove it in 0.21.0

**Comment by amaanq** [comment]
Ok, I also reworked it to not print out every group's name if it had no tests that would be run. I think this is cleaner overall

image

Before it'd be like this

image

Which feels annoying. Thanks for the PR!

**Pull request merged**
