### PR TITLE
feat: use cmake for cross-platform support

### PR DESCRIPTION
**Pull request by kylo252**
- use cmake by default to build the core library to support all platforms
- if cmake is not found, then fallback to using cc directly
- pkg-config is supported as well as find_package

fixes: #1366 #1518 #1686 #1737 #1732 #1262 #1246
related: #1555 #1749

### CODE REVIEW

**Comment by sogaiu** [comment]
May be related?

* https://github.com/tree-sitter/tree-sitter/pull/1749
* https://github.com/tree-sitter/tree-sitter/pull/1555

**Comment by kylo252** [comment]
@sogaiu, thanks for the reminder!

the main difference is that this actually lets cargo invoke cmake, which solves various problems when building tree-sitter-cli as well.

another benefit is removing the need for a few files:
- [`Makefile`](https://github.com/tree-sitter/tree-sitter/pull/1821/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52): superseded by `CMakeLists.txt`
-  [`.ccls`](https://github.com/tree-sitter/tree-sitter/pull/1821/files#diff-a1cf5f28b1bd6b58d29cf8bbde170fa2609eec01235628da57d9501c70ff6bc9) and [`compile_flags.txt`](https://github.com/tree-sitter/tree-sitter/pull/1821/files#diff-2aa54b3f37d506cf422efaa520bf70c9cd4573b6e51b222385641f263392e0ab): superseded by `compile_commands.json` which is generated by CMake

**Comment by aminya** [comment]
Well, I can add `cmake` to build.rs in #1555 and remove the makefile. But I don't think the maintainers are open to such changes. They have not even reviewed #1555 after one year.

**Comment by RichardHyde** [comment]
I used the [kyloi252/tree-sitter](https://github.com/kylo252/tree-sitter/tree/cmake-refactor/cli) and was able to successfully build tree-sitter cli on a Raspberry Pi 4 with Raspberry PI OS 64-bit if that's any help to anyone.

**Pull request closed without merging**
