### PR TITLE
fix(binding_rust): Update docs

### PR DESCRIPTION
**Pull request by Uzaaft**
Update docs to be what seems to be the correct way to use the rust bindings, based upon what's available here: https://crates.io/crates/tree-sitter-rust

### CODE REVIEW

**Comment by Uzaaft** [comment]
Fixes:
#1335
And makes:
#662
Not longer valid due to the change regarding `build.rs`

**Comment by Uzaaft** [comment]
@maxbrunsfeld Sorry about the ping, but you seemed to be the "lead" in this project.
Could you take a look at these changes for the rust docs? The current one seemed to be outdated.

**Comment by Uzaaft** [comment]
Tired of waiting for anyone to take a look. Closing this PR.

**Comment by ahlinc** [comment]
@Uzaaft one of my reasons to don't merge anything not very important was a CI that worked very unstable last months and until this week. And I didn't want to break the CI and keep people think that the project is broken most of the time.

Recently I rebased your branch on top of master to prepare it for a merge but you was faster and close this PR.

**Pull request closed without merging**
