### PR TITLE
add license to rust crate

### PR DESCRIPTION
**Pull request by solomoncyj**

### CODE REVIEW

**Comment by amaanq** [comment]
The only problem with this is that symlinks don't really work on windows

**Comment by solomoncyj** [comment]
Then just copy the file

**Comment by clason** [comment]
It's your PR....

**Comment by ObserverOfTime** [comment]
What's the point of this? The crate already specifies the license.

**Comment by LecrisUT** [comment]
> The only problem with this is that symlinks don't really work on windows

This has long been resolved, iirc more than 4 years ago

> What's the point of this? The crate already specifies the license. And we can't just copy the file to every single crate in this repo.

There are additional information that is not apparent from the SPDX license only, e.g. copyright authorship.

> Then just copy the file

Please update the PR and make a symlink for all the other crates as well

**Comment by clason** [comment]
> This has long been resolved, iirc more than 4 years ago

No, it has not.

**Comment by LecrisUT** [comment]
> > This has long been resolved, iirc more than 4 years ago
> 
> No, it has not.

Would you offer some more context to [this post](https://stackoverflow.com/a/59761201) then?

**Comment by clason** [comment]
> once you update your Windows understanding of mklink a bit and turn on Developer Mode.

So not out of the box.

**Comment by LecrisUT** [comment]
> > once you update your Windows understanding of mklink a bit and turn on Developer Mode.
> 
> So not out of the box.

You similarly need to setup your git author, email, commit signage, change default branch, etc. It's part of setting up a developer environment. Maybe the git installation can automate and prompt better, but you would need to take it up with the packagers in that case, maybe msys. Git itself supports it just well.

**Comment by clason** [comment]
Or we can simply not use symlinks in repos, which is _our_ choice. I don't understand why this is up for debate.

**Comment by LecrisUT** [comment]
There are various rust projects that do this and there is no complaints that it has broken any windows systems:
- https://github.com/launchbadge/sqlx
- https://github.com/milesgranger/blosc2-rs
- https://github.com/maciejhirsz/logos

And many other projects simply have copied files.

Afaiu the `git-archive` also handles the symlink for the curl workflows either by copying them or making appropriate links. Try it out on any of the above repos and let me know if you see those being broken either in plain windows gui or wsl.

The crate itself will have the resolved symlink so there is no issues for the eveyday user.

---

Whether or not the license files are necessary is a matter best left to a lawyer, and these stuff evolve as technology evolves. At the very least Fedora legal team has looked into the cargo packaging, and if you want feel free to get in touch with them to re-review it.

The cargo manifest does not take a stance on whether or not [`authors` field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field) is considered the copyright holder so the copyright is vague with a packaged license file.

**Pull request closed without merging**
