### PR TITLE
feat(wit): Add correct WIT lib to docs

### PR DESCRIPTION
**Pull request by liamwh**
corrects #3348

### CODE REVIEW

**Comment by liamwh** [comment]
Bump

**Comment by sogaiu** [comment]
Not sure what the policy is recently, but not too far back, I think updating this list was being done in batches (https://github.com/tree-sitter/tree-sitter/pull/2716#issuecomment-1773533861).

**Comment by liamwh** [comment]
Is anyone able to label this with the `doc-link` label then perhaps?

**Comment by sogaiu** [comment]
Not me AFAICT, but if you don't mind using [discord](https://discord.gg/w7nTvsVJhm) or [matrix](https://matrix.to/#/#tree-sitter-chat:matrix.org), I believe there are folks who can who hang out in one or the other or both of those, so possibly they could be notified there.

**Comment by amaanq** [comment]
We are no longer adding parsers to the main docs page - they now live at https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers, and a request can be made by joining the discord/matrix chat linked in that wiki and asking there.

**Pull request closed without merging**
