### PR TITLE
docs: add YAML/TOML parser

### PR DESCRIPTION
**Pull request by ikatyang**
- https://github.com/ikatyang/tree-sitter-yaml
- https://github.com/ikatyang/tree-sitter-toml

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Both of these look great; awesome work!

I noticed that you had to patch Tree-sitter to allow for `---` lines in the YAML tests. I'll try to fix that limitation sometime soon.

**Comment by maxbrunsfeld** [comment]
Since both of these are such popular languages, I added them to the playground on the website.

**Comment by maxbrunsfeld** [comment]
@ikatyang Ok, in https://github.com/tree-sitter/tree-sitter/commit/a8dedbee0d7ed8df0f359298577858703f6765c2, I *think* I've addressed the problem with `tree-sitter test` that you were having to patch.

Now, when parsing unit test files, in order to find the dividing line between input and expected output, Tree-sitter will look for the *longest* line of dashes, not the first line of dashes. So for YAML, you should be able to write the tests like this, if you want to:

```
===========================
Document start on last line
===========================
---
a: b
---

--------

(stream
  (document
    (block_node
      (block_mapping
        (block_mapping_pair
          key: (flow_node
            (plain_scalar))
          value: (flow_node
            (plain_scalar))))))
  (document))
```

**Comment by ikatyang** [comment]
Thanks, it [works](https://github.com/ikatyang/tree-sitter-yaml/commit/3439d6f2edc5487f7c3ce08c6a177bb8de88ff04)!

**Pull request merged**
