### PR TITLE
feat(cli)!: upgrade clap to v4 and rework cli args into structs

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by dundargoc** [comment]
I can't read rust but I can read CI colors. Rebase and merge?

**Comment by dundargoc** [comment]
Any blockers for this?

**Comment by amaanq** [comment]
Yeah sorry let me get to it!

**Comment by dundargoc** [comment]
Superseded by https://github.com/tree-sitter/tree-sitter/pull/2961

**Pull request closed without merging**
