### PR TITLE
feature: debug graph output on Windows

### PR DESCRIPTION
**Pull request by yehorb**
As I understand, dot graph output was essentially disabled on Windows, as file handles are not file descriptors.

Turns out, it is relatively easy to [get a file descriptor](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle?view=msvc-170) from a file handle, which works seamlessly with existing C code, with few exceptions.

By creating a simple wrapper file to cover platform differences, slightly altering `ffi` bindings, and enabling `print_tree_graph` and `log_graphs` functions, I managed to get proper dot graphs on Windows.

I found that there were no tests for the dot graph output specifically, so I carried out a bit of manual testing.

I tested the changes on some of my projects - mostly Python and Rust files, mostly around 100 lines of code. All of the resulting `log.html` files differed between platforms, but only in specifics due to dot rendering being slightly different. All of the generated texts and graphs were equivalent.

To verify the changes on a bigger file, I used the `tree-sitter-c` parser to parse the `lib/src/parser.c` file. Both on Windows and on Linux the `tree-sitter parse -D lib/src/parser.c` command produced a 500mb `log.html` file, both of which crashed my browser.

I was able to obtain the unprocessed `log.dot` file using [some hacks](https://github.com/tree-sitter/tree-sitter/commit/8c32d2436aac4ed7646c4e3b3fbf8e4dfe2158e7). These files were easier to reason about. While not identical, they had the same number of lines, and, from what I can tell, were equivalent, only differing in specifics such as concrete dot node names.

Overall, this seems to be working pretty well.

### CODE REVIEW

**Comment by ahlinc** [comment]
Thank you for proposing this contribute but currently I'll postpone it because we aren't ready to make API changes, there is an another idea to make Tree-sitter core lib fully dependency free and it requires an another approach to the API.

**Comment by yehorb** [comment]
> Thank you for proposing this contribute but currently I'll postpone it because we aren't ready to make API changes, there is an another idea to make Tree-sitter core lib fully dependency free and it requires an another approach to the API.

Thank you for the review. I hope either this or a similar solution will be implemented in the future. Not having debug graph output on Windows was very upsetting for me.

Just to clarify - is any change to the C code (and, but extension, to the `ffi` crate) considered an API change? Like, in this case, the addition of the new functions, even though they are internal use only and are not exposed via `tree_sitter/api.h` is still considered an API change?

I want to understand what is considered an API change to better plan any future contributions. I saw quite a few changes rejected or postponed due to them introducing "API changes", and it will be nice to understand what it entails.

**Comment by bitomukesh** [comment]
## PR Analysis

- **Main theme:** Enabling dot graph output on Windows by implementing cross-platform file descriptor handling.
- **PR summary:** This PR introduces a cross-platform solution for dot graph output, which was previously disabled on Windows. It achieves this by wrapping platform-specific file descriptor/handle operations, allowing the existing C code to work seamlessly on both Unix and Windows systems.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 85
- **Relevant tests added:** No
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 3
The PR includes changes across multiple files with platform-specific code, requiring careful review to ensure compatibility and correct behavior on all supported platforms.
## PR Feedback

- **General suggestions:** The PR successfully addresses the issue of enabling dot graph output on Windows, which is a significant enhancement for Windows users of the project. The approach taken to abstract the file descriptor/handle operations into a cross-platform interface is commendable. However, it is critical to ensure that the new code does not introduce regressions or platform-specific bugs. It would be beneficial to include automated tests that verify the behavior on both Unix and Windows platforms. Additionally, the maintainers should consider the long-term maintainability of the platform-specific code and whether it aligns with the project's standards and practices.
## Code feedback

## file: lib/src/dot_graph_io.c

- **Suggestions:**



 1. Consider error handling for `DuplicateHandle` and `_open_osfhandle` to ensure robustness, especially since these are critical points of failure on Windows. [important] **Relevant line**:In lib/src/dot_graph_io.c at line 11
 ```
+ DuplicateHandle(
 ```


 2. Validate the `handle` argument before using it in `ts_dot_graph_io_make_fd` to prevent undefined behavior if a null or invalid handle is passed. [important] **Relevant line**:In lib/src/dot_graph_io.c at line 8
 ```
+int ts_dot_graph_io_make_fd(HANDLE handle) {
 ```


 3. To improve readability, consider defining platform-specific constants or functions for the flags used in `DuplicateHandle` and `_open_osfhandle`. [medium] **Relevant line**:In lib/src/dot_graph_io.c at line 15
 ```
+ DUPLICATE_SAME_ACCESS
 ```
## file: cli/src/util.rs

- **Suggestions:**



 1. Ensure that the removal of the platform-specific conditionals does not inadvertently change the behavior on Unix systems. [important] **Relevant line**:In cli/src/util.rs at line 3
 ```
-#[cfg(unix)]
 ```


 2. Since `LogSession` is now used on Windows as well, ensure that all members are properly initialized and used on both platforms. [important] **Relevant line**:In cli/src/util.rs at line 28
 ```
+pub struct LogSession {
 ```
## file: lib/binding_rust/ffi.rs

- **Suggestions:**



 1. Verify the safety and correctness of the new FFI bindings, especially the use of raw pointers on Windows, which can lead to undefined behavior if not handled carefully. [important] **Relevant line**:In lib/binding_rust/ffi.rs at line 11
 ```
+ pub(crate) fn ts_dot_graph_io_make_fd(
 ```
## file: lib/src/lib.c

- **Suggestions:**



 1. Confirm that the inclusion of `dot_graph_io.c` does not introduce any build issues on platforms where it was previously not required. [medium] **Relevant line**:In lib/src/lib.c at line 4
 ```
+#include "./dot_graph_io.c"
 ```

**Comment by bitomukesh** [comment]
We encountered a technical difficulties while attempting to generate code feedback

**Comment by bitomukesh** [comment]
We encountered a technical difficulties while attempting to generate code feedback

**Comment by clason** [comment]
PR comment feedback: Go away, AI troll!

**Comment by bitomukesh** [comment]
> PR comment feedback: Go away, AI troll!
> 
> @amaanq

Apologies if the auto-analysis of PR with LLMs violated any of the policies.  Would love to understand why such analysis is not welcomed. Is it that the quality of the analysis is not good, and it doesn't help improve the quality? Or it is just angst against the AI? Don't you think that AI can help the open-source community?

**Comment by clason** [comment]
It's unwelcome because it was unasked for and spammy. The onus is on _you_ to argue that generative models provide value over noise; the correct approach would have been to contact the maintainers privately or in an issue and ask whether such analysis would be welcome, explaining what would happen and -- most importantly -- what data would be used and how. Generative models of unknown provenance are toxic.

**Comment by bitomukesh** [comment]
Well, thanks for that comment. Definitely will ask the maintainer. Are human reviewers required to get permission before reviewing the code?  What if a contributor uses a tool like Github Copilot to complete the code, and contribute here? Does this project have checks and balances in place to detect that, or a code of conduct that says don't use Copilot to contribute? Just asking you and the community around this project on their PoV. 

We love open-source projects and communities, and there are many communities (such as LangChain) that welcome high-quality reviews through AI. We use models like GPT-4, Anthropic, and Google Gemini, the top three models in the world, and it costs several dollars per PR review that we are funding. I may not be able to convince you whether they are proven or not or are toxic, that's for you to decide. But, you reporting a review done through AI as spam, and models as AI trolls sound short-sighted. 

In general, there is angst between open-source communities and models like OpenAI, and Anthropic but these models are likely to stay, enterprises are adopting them, and open-source communities can benefit from it as well. Just need to be open-minded. 

Community/maintainer can of course avoid this debate by removing this post or AI, but a constructive dialog is more beneficial in my opinion.

**Comment by clason** [comment]
Also, not disclosing commercial affiliation is a huge red flag. It's not angst, it's warranted skepticism. And, again, if you want to engage in a community, spend some time getting to know that community -- every one is different. This is another reason (basically a definition!) why such unsolicited, out of the blue, "contributions" are considered spam.

**Comment by dundargoc** [comment]
Superseded by https://github.com/tree-sitter/tree-sitter/pull/2938

**Pull request closed without merging**
