### PR TITLE
feat: add `ts_query_cursor_set_max_depth()`

### PR DESCRIPTION
**Pull request by lewis6991**
This allows configuring cursors from traversing too deep into a tree.

Resolves: #1673, #1212

Implements: https://github.com/tree-sitter/tree-sitter/discussions/845#discussioncomment-206310

### CODE REVIEW

**Comment by ahlinc** [comment]
I'd better want to see this as a query language improvement like:
```scheme
(..5
  (identifier)
)

(2..
  (identifier)
)

(2..5
  (identifier)
)
```
Because this would allow to share this as a correct queries between different consumers without a custom logic that need to be re-implemented / duplicated.

**Comment by lewis6991** [comment]
For the applications I intend this for, the depth would be dynamic and based on editor settings.

For example I want to use this for neovims code folding which has a `foldnestmax` option.

Another application is code contexts which will implicitly always want the depth as zero.

Is there a compromise where this can be controlled at the query iteration level with room to expand into the queries themselves?

**Comment by lewis6991** [comment]
Excellent, good to know we can progress here.

I'll try and get a test or two in place before this can be merged. Otherwise the code should be reviewable.

**Comment by lewis6991** [comment]
Tests added, should be ready now.

**Comment by clason** [comment]
@lewis6991 lint seems to fail on the Rust code.

**Comment by clason** [comment]
@ahlinc I don't want to be pushy, but it would be really nice to have this included in the 0.20.8 release ;)

**Comment by clason** [comment]
Looks like someone merged master into this PR instead of rebasing?

**Comment by ahlinc** [comment]
> Looks like someone merged master into this PR instead of rebasing?

Yes, I've rebased it to run this PR on top of latest CI/CD changes. The noise in PR changes looks like a Github [web UI bug](https://github.com/tree-sitter/tree-sitter/pull/2126#issuecomment-1495799618).

**Comment by ahlinc** [comment]
@lewis6991 I'm +1 for the second case. Could you add such improvement?

**Comment by ahlinc** [comment]
@lewis6991 with the latest change some tests didn't passed correctly.

**Comment by clason** [comment]
Tests are passing now?

**Comment by clason** [comment]
@ahlinc friendly ping; tests pass now!

**Comment by smoelius** [comment]
Would it be possible to get a new release with this feature?

**Comment by ahlinc** [comment]
@smoelius https://github.com/tree-sitter/tree-sitter/issues/2247#issuecomment-1540014939

**Comment by smoelius** [comment]
Thanks for your prompt response, @ahlinc. :pray:

**Pull request merged**
