### PR TITLE
Package.swift: delete needless excludes

### PR DESCRIPTION
**Pull request by dabrahams**
They have no effect, since the one source file is specified explicitly.

### CODE REVIEW

**Review by ObserverOfTime — COMMENTED** [review]
Can you also delete this?
https://github.com/tree-sitter/tree-sitter/blob/7e3f57265549f26f4fe3ac1ee8ee3b1c6ee182f4/cli/src/generate/templates/package.swift#L17

**Comment by dabrahams** [comment]
> Can you also delete this?

I'm confused; [the diff](https://github.com/tree-sitter/tree-sitter/pull/3631/files) says I did delete line 17.  What am I missing?

**Comment by dabrahams** [comment]
done.

**Comment by amaanq** [comment]
ty!

**Pull request merged**
