### PR TITLE
Add ";" as comment in s-expressions

### PR DESCRIPTION
**Pull request by marcel0ll**
Remove everything after a ";" 

So
```
; Comment
(a 
  ; Comment
  (b)
)
```

Becomes
```
(a (b))
```

Related issue: https://github.com/tree-sitter/tree-sitter/issues/752

### CODE REVIEW

**Comment by marcel0ll** [comment]
Have to take into account ";" in languages...

**Comment by marcel0ll** [comment]
Apparently, error during tests is due to a change in the ruby grammar that was already incorporated inside tree-sitter tests but not actually released by tree-sitter-ruby.

I could not think of a reliable way to write a regex that would understand the difference between s-expression containing a ";", ex: '(MISSING ";"), 'and a final "; comment" so I this PR would only accept comments at line start.

**Comment by maxbrunsfeld** [comment]
This is great work. Thanks for writing a good test for it as well, and sorry for the long delay in merging.

**Comment by marcel0ll** [comment]
Glad to contribute

**Pull request merged**
