### PR TITLE
Add a link to `tree-sitter-wit`

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**

### CODE REVIEW

**Comment by sogaiu** [comment]
Curious how this differs from the other two listed [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/List-of-parsers) (though I guess one of those two looks a little old).

**Comment by Michael-F-Bryan** [comment]
The parser from @hh9527 seems to be for an older  WIT syntax from before the concepts of "packages" and "worlds" were introduced.

It looks like both my parser and @liamwh are essentially equivalent, although I believe my version has more testing and is currently used by the Language Server in that repo.

**Comment by liamwh** [comment]
I agree that the parser from @hh9527 is out of date and should not be used.

I would propose adding my [tree-sitter-wit](https://github.com/liamwh/tree-sitter-wit) to this list instead as it is used daily "in-production" (developers' Neovim instances) and installable via [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). My version is actively maintained and I intend to continue to maintain it as the [WIT spec](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md) evolves, and consequently hope that no more `tree-sitter-wit` libraries appear. @Michael-F-Bryan  if you feel you have any improvements I would recommend making a PR to my repo, though I'm not aware of any at this time (besides maybe publishing the NPM/Crates.io/PyPI packages).

**Comment by Michael-F-Bryan** [comment]
@liamwh I'm happy to link to your parser in preference to mine. It's one less thing for me to maintain and worry about, and if you are using it in production then that's a pretty good guarantee it'll stay up to date 🙂 

If it's alright with you, I might also make a PR to your repo to add my test cases and a couple of modifications I've made to the Rust bindings (mostly tests).

@sogaiu, I'll close this issue in favour of #3349.

**Pull request closed without merging**
