### PR TITLE
Fix error recovery regression due to stack node_count change

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Fixes https://github.com/tree-sitter/tree-sitter/issues/2443

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
I wish this regression were caught by tests. I guess the behavior mattered more for some languages than others. And error recovery is somewhat difficult to test.

I'm gonna merge this for now. In the future, I'd like to better job testing in this area.

**Comment by amaanq** [comment]
We could add the cases caught by scala or scheme, but that'd require adding those grammars to fixtures

**Comment by maxbrunsfeld** [comment]
Yeah, I guess scala or PHP would be good options, since they are under the Tree-sitter org.

**Comment by llllvvuu** [comment]
Noting that there's a performance regression in Neovim after this commit:

https://github.com/neovim/neovim/issues/25252

(I don't suspect this commit yet, but it is behaving differently somehow)

**Pull request merged**
