### PR TITLE
Docs: add links to XML and Objective-C++ parsers

### PR DESCRIPTION
**Pull request by logancollins**
This pull request adds links to the `docs/index.md` file for two additional parsers (XML and Objective-C++), which are now available via @panicinc.

Additionally, it adds `.DS_Store` to the `.gitignore` file just because I have to clean away those a lot being on a Mac. 😅

### CODE REVIEW

**Comment by logancollins** [comment]
This has been sitting unreviewed for quite a bit. Would one of the team be able to do so? If the project isn't interested in linking to these grammars, I understand!

**Comment by sogaiu** [comment]
Possibly of interest might be [this](https://github.com/tree-sitter/tree-sitter/pull/2716#issuecomment-1773533861).

**Comment by logancollins** [comment]
> Possibly of interest might be [this](https://github.com/tree-sitter/tree-sitter/pull/2716#issuecomment-1773533861).

Ah, good to know. Thank you!

**Comment by amaanq** [comment]
We are no longer adding parsers to the main docs page - they now live at https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers, and a request can be made by joining the discord/matrix chat linked in that wiki and asking there.

**Comment by logancollins** [comment]
> We are no longer adding parsers to the main docs page - they now live at https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers, and a request can be made by joining the discord/matrix chat linked in that wiki and asking there.

No worries, and thank you!

**Pull request closed without merging**
