### PR TITLE
fix(tests): sort categories alphabetically

### LINKED ISSUE #373: Tree sitter test result order depends on platform
So it seems running `tree-sitter test` is working differently on windows/macos vs linux.

In windows and macos the categories are ordered alphabetical:
https://ci.appveyor.com/project/Razzeee/tree-sitter-elm/builds/25599909/job/tn1uy8u5oqpurkqw
https://ci.appveyor.com/project/Razzeee/tree-sitter-elm/builds/25599909/job/jvqcokahmm06udtb
https://travis-ci.org/Razzeee/tree-sitter-elm/jobs/551541116

But in linux the don't seem to be ordered by category:

https://travis-ci.org/Razzeee/tree-sitter-elm/jobs/551541117

### PR DESCRIPTION
**Pull request by amaanq**
Closes #373

@razzeee I know this is old but can you try this out? Seems to work on my Linux machine for Elm's tests

image

### CODE REVIEW

**Comment by razzeee** [comment]
I will need some time to get back to this and dig back into how tree-sitter does stuff :)

**Comment by razzeee** [comment]
I have no idea how to run elm tree sitter with a feature branch of tree sitter anymore. I think I would be fine trusting your testing here :)

**Comment by amaanq** [comment]
You can install my branch with `cargo install --path cli` and then as long as your cargo bin path is in your $PATH, you can run `where tree-sitter` to see if it'll use that.

**Comment by razzeee** [comment]
Can confirm, categories are now sorted. I don't remember if the tests on win/mac where also ordered and I don't think I'm running win/mac tests anymore.

**Pull request merged**
