### PR TITLE
refactor(tests): migrate remaining `grammar.json` tests to `grammar.js`

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for doing this!!

**Comment by hernanitop15172** [comment]
USD dollar $900,000,0000 hernanitopoblacion@gmail.com

**Review by Romek-cloud — COMMENTED** [review]
Finish

**Review by Romek-cloud — COMMENTED** [review]
Path

**Pull request merged**
