### PR TITLE
Add CMake support for tree_sitter C library

### PR DESCRIPTION
**Pull request by aminya**
- This adds cross-platform CMake support for the tree_sitter C library. 
- This also helps the IDEs to work correctly (autocomplete, showing the warnings in the code, etc.) by generating the required `compile_command.json` for clangd or MSVC. e.g. automatic refactoring was used in #1618
- Enables the compiler warnings. For example, see the shadowed variables revealed by PR #1618. The CMake is based on the cpp-best-practices project, which helps the project evolve. 
 
- This cmake file generates a tree-sitter package, which allows it to be used from other projects and potentially added to the C++/C package managers like vcpkg and Conan
```cmake
    find_package(tree-sitter CONFIG REQUIRED)
    target_link_libraries(main PRIVATE  tree-sitter::tree_sitter tree-sitter::project_options tree-sitter::project_warnings)
```
image

- optionally, you can remove the old Makefile as it doesn't have any of the above-mentioned points.

### CODE REVIEW

**Comment by hinell** [comment]
> _cpp-best-practices_

Link?

**Comment by aminya** [comment]
> > _cpp-best-practices_
> 
> Link?

https://github.com/cpp-best-practices
https://github.com/cpp-best-practices/project_options

**Comment by aminya** [comment]
Is there any incentive to merge these pull requests?

**Comment by sogaiu** [comment]
Possibly this comment is relevant? https://github.com/tree-sitter/tree-sitter/pull/1749#issuecomment-1133133159

**Comment by aminya** [comment]
I think it is more important to add new maintainers as many issues are not being addressed. For example, 

https://github.com/tree-sitter/node-tree-sitter/issues/111


I would be personally happy to maintain the tree-sitter. But I have not heard back from @maxbrunsfeld regarding that.

**Comment by hinell** [comment]
@aminya It certainly would be nice to have more maintainers.

**Comment by aminya** [comment]
@maxbrunsfeld  Thanks for the reply! 

Did you check my comment at 
https://github.com/tree-sitter/tree-sitter/pull/1555#issuecomment-1200357986

I'd like to maintain this addition and any other thing that Tree-Sitter needs help with.

**Comment by pbrubaker** [comment]
I certainly would appreciate this being merged.  We are using TS for a cross platform LSP for the ISPC language, and creating C# bindings for the API.  Not having out of the box cross-platform compile functionality was disappointing.  This PR will help us a lot.  Thanks @aminya.

**Comment by SamuelMarks** [comment]
I'm still open to contributing CMake support (see my #1749 and friends). There are a number of odd use-cases I want to support, that CMake greatly simplifies.

**Comment by aminya** [comment]
The issue seems to be that the tree-sitter project is not interested in adding contributors or maintainers. 

 I have been maintaining my fork for years now.
I treat this project like a closed project these days.

**Comment by amaanq** [comment]
Well, I don't think your dependency on a project necessitates you to be a maintainer of said project, but I do agree there should be a couple more active maintainers (especially to help w/ the outdated releases of some grammars that have gotten performance improvements lately)

**Comment by aminya** [comment]
> & to not get off-topic, is CMake really necessary? All I can think of benefits-wise is that it could help with Windows building, testing is easy to do cross-platform-wise with Rust

Actually, there are many problems with the current build system. See these issues I created and their open PRs that have been left unattended:
https://github.com/tree-sitter/tree-sitter/issues/1889
https://github.com/tree-sitter/tree-sitter/pull/1835
https://github.com/tree-sitter/tree-sitter/pull/1411
https://github.com/tree-sitter/tree-sitter/pull/1411

**Comment by amaanq** [comment]
Yes, that alludes to my point..CMake would help building on Windows, though it's unfortunate they've been left unattended

**Comment by sogaiu** [comment]
The idea of one's repository hosting something that a current maintainer doesn't really look after in detail seems to be one that tree-sitter itself has arranged for across many if not all of its grammars.  Specifically I mean the Node and Rust bindings.  These are automatically generated and thus end up in many repositories and yet the maintainers of those grammars don't necessarily test them (I don't imagine I'm alone in that, though it seems likely there are some people who do).  Yet, it is presumably found to be useful by some.

I removed such bindings from a couple of the grammars I looked after (with no complaints so far) so I can relate to not wanting to include such files, but if someone appropriate came along, I might reconsider.

I think it's pretty clear from the history here that CMake support would be beneficial to some (and there are people who have volunteered to help look after as well) and it's not an isolated type of situation.  For example, the recent PR for a Swift-related file:

https://github.com/tree-sitter/tree-sitter/pull/2311

seems in a similar neighborhood.

I wonder if it's not an option to clearly document that some files are in the repository because of user requests and their maintenance status is not the same?

As a comparison, I received a similar request for a grammar repository and ended up including a query file that I did not intend to have for the sake of a user (difftastic).

**Comment by maxbrunsfeld** [comment]
> I would be personally happy to maintain the tree-sitter as my projects rely on that. But I have not heard back from @maxbrunsfeld regarding that.

Sorry for the delay. I think these files are totally usable via a separate repository, and don't need to be part of this one. Most Tree-sitter users don't need this, and those that do can pull in the CMake config from your repository.

I'm going to close this out, as this doesn't need to be added to the main Tree-sitter repository. Thanks for developing this though. Feel free to open a PR to add a link to your repo into the docs.

**Pull request closed without merging**
